---
title: "Lista I: Desenho de pesquisa"
date: "03/04/2026"
author:
  - name: Davi Athaydes Leite
    email: davileite@iesp.uerj.br
abstract: > 
  Inserir resumo sobre a resolução da lista.
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
    fig-pos: 'H'
    df-print: kable
    geometry:
      - top=25mm
      - left=20mm
      - right=20mm
      - bottom=25mm
bibliography: ../referencias.bib
lang: pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Pacotes (instale os que ainda não tiver com install.packages())
library(tidyverse)
```

# Bloco I – Definição do problema de pesquisa

## Delimitação disciplinar

### Resposta

Política distributiva. 

## Problema de pesquisa

### Resposta

Quais fatores políticos influenciam a distribuição do orçamento discricionário federal entre os municípios brasileiros?

## Definição de conceitos

### Resposta

Em relação à variável dependente do estudo, é possível definir o orçamento discricionário da união como a parcela do Orçamento Geral da União (OGU) cujos recursos não possuem vinculação legal ou institucional obrigatória, conferindo discricionariedade à União [@moutinho_transferencias_2016]. Quanto aos fatores explicativos, é possível exemplificar o alinhamento partidário entre executivo federal e municipal, e o apoio eleitoral conferido ao presidente eleito naquele ente subnacional *(Citar?)*.

## Operacionalização de variáveis

### Resposta

A variável dependente pode ser mensurada a partir das Transferências Voluntárias da União (TVU) aos municípios, por meio de convênios. É possível construir uma variável contínua para cada município, que represente o montante (em reais) recebido via convênios no ano^[O link para a fonte destes dados pode ser encontrado em: [Convênios da União](https://dados.gov.br/dados/conjuntos-dados/convenios-do-poder-executivo-federal).]. Cada observação é um município, e a unidade de análise o total recebido por esse ente no respectivo ano. O alinhamento partidário pode ser operacionalizado de forma binária (1 = prefeito correligionário; 0 = prefeito de outro partido).

## Variáveis

### Resposta

A variável dependente é o montante recebido via convênios no ano pelo município. O alinhamento partidário é um fator explicativo (variável independente). 

# Bloco II – Teoria e hipóteses

## Teoria causal

### Resposta

Por que fatores políticos como o alinhamento partidário afetariam a distribuição de recursos da União? (Se basear na literatura distributiva - Favorecimento das bases eleitorais - Pereira e Mueller)

## Hipótese principal

## Implicações testáveis ou hipóteses secundárias (mecanismo)

# Bloco III – Montando o desenho

## Desenho de pesquisa

\newpage

### Referências

::: {#refs}
:::
