---
title: "Lista 2: Desenho de pesquisa"
date: "05/05/2026"
author:
  - name: Davi Athaydes Leite
    email: davileite@iesp.uerj.br
abstract: > 
  xx    
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
    fig-pos: 'H'
    df-print: kable
    geometry:
      - top=25mm
      - left=20mm
      - right=20mm
      - bottom=25mm
bibliography: ../referencias.bib
lang: pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(showtext)
library(knitr)

## add fonte do google para plots
font_add_google("Open Sans", "open_sans")

## ativar showtext
showtext_auto()

```

\newpage

## 1. Importação

```{r}
#| label: tarefa_1

artigos <- readRDS("data/artigos.rds")


periodicos_ciencias_sociais <- read_delim(
  "data/periodicos_ciencias_sociais.csv",
  delim = ";", escape_double = FALSE, trim_ws = TRUE) |> 
  mutate(
    issn = paste0(substr(issn, 1, 4), "-", substr(issn, 5, nchar(issn)))
  )


artigos_dados <- left_join(artigos,
                           periodicos_ciencias_sociais,
                           by = "issn")


artigos_destaque <- artigos_dados |>
  filter(quartil %in% c("Q1", "Q2", "Q3"))

rm(artigos)
rm(periodicos_ciencias_sociais)

```

## 2. Seleção de palavras-chave

```{r}
#| label: tarefa_2

artigos_selecionados <- artigos_destaque |> 
  mutate(abstract = tolower(abstract)) |>
  filter(
    str_detect(
      abstract, paste(c("transfer", "discricionar", 
                        "coalizao"), collapse = "|")
    )
  )
```

## 3. Evolução ao longo do tempo

```{r}
#| label: tarefa_3
#| fig-align: center
#| fig-cap: "Total de artigos publicados por ano"

artigos_selecionados |> 
  group_by(ano) |> 
  summarise(total_artigos = n()) |>
  
  ggplot()+
  aes(x = ano, y = total_artigos)+
  geom_line(color="#818589",
            size=1, alpha=0.9) +
  
  geom_point(shape=21, color="black", fill="#818589", size=1.5) +
  ylim(0,8)+
  scale_x_continuous(breaks = seq(2001, 2025, 1))+
  labs(x = "Ano",
       y = "Total de artigos")+
  theme_minimal(base_family = "open_sans")+
  theme(
    axis.text.x  = element_text(size = 6, face = "bold",
                                angle = 45, hjust = 1),
    axis.text.y  = element_text(face = "bold"),
    axis.title.y = element_text(size = 8, face = "bold"),
    axis.title.x = element_text(size = 8, face = "bold"),
    legend.text  = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  )

```


## 4. Relevância bibliométrica ao longo do tempo

```{r}
#| label: tarefa_4
#| fig-align: center
#| fig-cap: "Número total e médio de citações, por ano"

artigos_selecionados |> 
  group_by(ano) |> 
  summarise(
    total_citacoes = sum(citacoes_recebidas),
    media_citacoes = mean(citacoes_recebidas)
  ) |> 
  pivot_longer(
    cols = c(total_citacoes,media_citacoes),
    names_to = "metrica"
  ) |>
  ggplot()+
  aes(x = ano, y = value, color = metrica)+
  geom_line(size=1, alpha=0.9)+
  geom_point(aes(fill = metrica, color = metrica),
             shape = 21, size = 1.5)+
  ylim(0,130)+
  scale_x_continuous(breaks = seq(2001, 2025, 1))+
  scale_color_manual(values = c("#818589", "#6082B6")) +
  scale_fill_manual(values = c("#818589", "#6082B6"))+
  labs(color = "", fill = "",
       x = "Ano", y = "Total / Média")+
  theme_minimal(base_family = "open_sans")+
  theme(
    legend.position = "bottom",
    axis.text.x  = element_text(size = 6, face = "bold",
                                angle = 45, hjust = 1),
    axis.text.y  = element_text(face = "bold"),
    axis.title.y = element_text(size = 8, face = "bold"),
    axis.title.x = element_text(size = 8, face = "bold"),
    legend.text  = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  )


```


## 5. Evolução relativa 


```{r}
#| label: tarefa_5
#| fig-align: center
#| fig-cap: "Proporção de artigos do tema em destaque, por ano"

artigos_destaque |>
  mutate(
    artigos_tema = if_else(
      str_detect(abstract, paste(c("transfer", "discricionar", "coalizao"),
                                 collapse = "|")), 1, NA
    )
  ) |>
  group_by(ano) |> 
  summarise(
    total_artigos = n(),
    total_artigos_tema = sum(artigos_tema, na.rm = TRUE)
  ) |>
  mutate(
    proporcao_artigos = total_artigos_tema/total_artigos
  ) |> 
  
  ggplot()+
  aes(x = ano, y = proporcao_artigos)+
  geom_line(color="#818589",
            size=1, alpha=0.9)+
  ylim(0,0.3)+
  scale_x_continuous(breaks = seq(2001, 2025, 1))+
  geom_point(shape=21, color="black", fill="#818589", size=1.5)+
  labs(x = "Ano", y = "Proporção")+
  theme_minimal(base_family = "open_sans")+
  theme(
    axis.text.x  = element_text(size = 6, face = "bold",
                                angle = 45, hjust = 1),
    axis.text.y  = element_text(face = "bold"),
    axis.title.y = element_text(size = 8, face = "bold"),
    axis.title.x = element_text(size = 8, face = "bold"),
    legend.text  = element_text(face = "bold"),
    legend.title = element_text(face = "bold")
  )

```


## 6. Produção por periódico

```{r}
#| label: tarefa_6
#| tbl-cap: "Relação de periódicos que mais publicaram sobre o tema"

producao_periodicos <- artigos_selecionados |> 
  group_by(revista) |> 
  summarise(total_artigos = n()) |> 
  arrange(-total_artigos) |> 
  slice(0:4) |> 
  rename(
    Revista = revista,
    `Total de artigos` = total_artigos
  )

kable(producao_periodicos)

```


